-- ============================================================
--  EHS Incident Portal — Sample Data Seed
--  Paste this entire file into the Supabase SQL Editor and Run
-- ============================================================

INSERT INTO incidents (
  incident_id, status, incident_type, urgency, incident_date, incident_time,
  incident_site, incident_area, description, immediate_actions, equipment_involved,
  person_type, involved_first, involved_last, employee_id, job_title, department,
  hire_date, supervisor_name, supervisor_email,
  injury_type, body_area, body_part, days_away, days_restricted,
  medical_treatment, work_related, osha_recordable, osha_result,
  root_cause_category, training_deficiency, rca_method,
  witnesses, corrective_actions, five_whys, attachments,
  reporter_first, reporter_last, reporter_email, reporter_phone,
  reporter_dept, reporter_site, reporter_title,
  submitted_at, updated_at
) VALUES

-- 1. Slip/fall injury — Deer Park
('INC-2026-03-0101','Open','injury','high','2026-03-18','07:45',
 'Deer Park','Unit 3','Employee slipped on wet grating near Pump P-203 while performing scheduled preventive maintenance. The drain cover was dislodged and water had accumulated on the walkway. Employee landed on right knee. Supervisor was immediately notified and first aid was administered on-site.',
 'Applied ice pack and compression wrap on-site. Supervisor notified. Area barricaded pending repair.',
 'Pump P-203',
 'employee','Marcus','Rivera','EMP-047','Maintenance Technician','Maintenance',
 '2021-04-12','Tony Rodriguez','tony.rodriguez@company.com',
 'Fall — Same Level','Lower Extremity','Right knee',3,0,
 'Physician / clinic visit','yes',true,'Recordable — Days Away From Work (3 days)',
 'environment',true,'whys',
 '[{"name":"David Chen","phone":"(713) 555-0182","statement":"Witnessed the slip from approximately 15 feet away. Drain cover appeared dislodged."}]',
 '[{"description":"Repair all dislodged drain covers in Unit 3 walkways","assignee":"Tony Rodriguez","due_date":"2026-03-25","status":"Open","priority":"high"}]',
 '[{"why":"Why 1","answer":"Employee slipped on standing water on walkway"},{"why":"Why 2","answer":"Drain cover was dislodged and not reported"},{"why":"Why 3","answer":"No pre-shift walkway inspection was conducted"},{"why":"Why 4","answer":"Inspection checklist did not include drain cover verification"},{"why":"Why 5","answer":"SOP for wet-weather inspections had not been updated since 2019"}]',
 '[]',
 'Angela','Brown','safety@company.com','(713) 555-0100',
 'Safety','Deer Park','HSE Coordinator',
 '2026-03-18T09:12:00Z','2026-03-18T09:12:00Z'),

-- 2. Near miss — Baytown
('INC-2026-03-0102','Closed','nearmiss','medium','2026-03-15','14:30',
 'Baytown','Loading Dock A','Near-miss observed during forklift loading operations. A pedestrian stepped into the forklift travel lane without using the designated walkway. Forklift operator stopped in time with approximately 3 feet of clearance. No contact was made.',
 'Forklift operation halted. Pedestrian escorted from area. Incident documented and reported to shift supervisor.',
 'Forklift FL-07',
 'employee','Jessica','Park','EMP-031','Logistics Coordinator','Logistics',
 '2019-08-20','Karen Davis','karen.davis@company.com',
 '','','',0,0,
 'First aid only','yes',false,'Not recordable — Near miss/observation',
 'procedure',false,'fishbone',
 '[]',
 '[{"description":"Repaint pedestrian crossing markings at Loading Dock A","assignee":"Karen Davis","due_date":"2026-03-22","status":"Closed","priority":"medium"},{"description":"Conduct forklift safety briefing for all logistics staff","assignee":"Karen Davis","due_date":"2026-03-20","status":"Closed","priority":"high"}]',
 '[]','[]',
 'Robert','Thompson','safety@company.com','(713) 555-0100',
 'Safety','Baytown','Safety Officer',
 '2026-03-15T15:45:00Z','2026-03-20T10:30:00Z'),

-- 3. Chemical exposure — Texas City
('INC-2026-03-0103','In Progress','illness','immediate','2026-03-12','10:15',
 'Texas City','Pump Station 2','Employee was exposed to sodium hydroxide (NaOH) caustic solution during a routine valve inspection when a flange fitting failed unexpectedly. Approximately 2 liters of 30% NaOH solution contacted the employee''s left forearm through the sleeve gap in PPE. Employee was immediately taken to the site medical clinic.',
 'Employee escorted to site clinic immediately. Exposed area flushed with water for 20 minutes per SDS. Supervisor and HSE notified. Area isolated.',
 'Valve V-552, Chemical: Sodium Hydroxide (30%)',
 'employee','Antonio','Vasquez','EMP-089','Operator II','Operations',
 '2018-02-14','John Martinez','john.martinez@company.com',
 'Chemical Exposure','Upper Extremity','Left forearm',0,5,
 'Emergency room visit','yes',true,'Recordable — Job Transfer / Restricted Duty (5 days)',
 'equipment',true,'whys',
 '[{"name":"Sandra Lee","phone":"(713) 555-0244","statement":"Was present when flange failed. Employee reacted quickly. PPE gap was visible."}]',
 '[{"description":"Inspect all similar flange fittings on caustic service lines","assignee":"John Martinez","due_date":"2026-03-19","status":"Open","priority":"critical"},{"description":"Review PPE specification for caustic service — sleeve length requirements","assignee":"Angela Brown","due_date":"2026-03-26","status":"Open","priority":"high"}]',
 '[{"why":"Why 1","answer":"Flange gasket failed causing NaOH release"},{"why":"Why 2","answer":"Gasket had exceeded its service life"},{"why":"Why 3","answer":"PM schedule for gasket inspection was 3 years overdue"},{"why":"Why 4","answer":"Asset tag system did not flag overdue PM for this equipment class"},{"why":"Why 5","answer":"Preventive maintenance scope did not include flange gaskets on non-critical service lines"}]',
 '[]',
 'Michael','Santos','safety@company.com','(713) 555-0100',
 'Safety','Texas City','HSE Coordinator',
 '2026-03-12T11:30:00Z','2026-03-14T08:00:00Z'),

-- 4. Vehicle incident — La Porte
('INC-2026-02-0201','Closed','vehicle','high','2026-02-28','16:00',
 'La Porte','Parking Lot','Company vehicle (Truck #V-14) was involved in a minor collision in the facility parking lot during end-of-shift. Driver was pulling out of a parking space and made contact with a stationary vehicle. No injuries. Estimated property damage of $2,200 to both vehicles.',
 'Both vehicles moved to designated area. Insurance information exchanged. Incident reported to fleet manager and security.',
 'Truck V-14',
 'employee','Brian','Nguyen','EMP-055','Shift Supervisor','Operations',
 '2015-09-01','Sarah Thompson','sarah.thompson@company.com',
 '','','',0,0,
 'First aid only','yes',false,'Not recordable',
 'human-error',false,'bowtie',
 '[]',
 '[{"description":"Schedule defensive driving refresher for all company vehicle operators","assignee":"Sarah Thompson","due_date":"2026-03-15","status":"Closed","priority":"medium"}]',
 '[]','[]',
 'Jennifer','Williams','safety@company.com','(713) 555-0100',
 'Safety','La Porte','Safety Officer',
 '2026-02-28T17:15:00Z','2026-03-10T14:00:00Z'),

-- 5. Struck by object — Pasadena
('INC-2026-02-0202','Pending Review','injury','high','2026-02-20','09:30',
 'Pasadena','Maintenance Bay','Employee was struck on the left shoulder by a falling pipe section (6-inch, 8 lbs) that dislodged from a temporary storage rack during a crane lift operation. The rigger''s load was not properly secured and the auxiliary hook caught the stored material. Employee was wearing a hard hat but the impact was to the shoulder.',
 'First aid applied. Employee transported to clinic. Crane operation suspended. Scene preserved for investigation.',
 'Crane CR-02, Pipe Section (6" dia)',
 'employee','Carlos','Mendez','EMP-072','Pipefitter','Maintenance',
 '2020-06-10','Mike Chen','mike.chen@company.com',
 'Struck By Object','Upper Extremity','Left shoulder',2,3,
 'Physician / clinic visit','yes',true,'Recordable — Days Away From Work (2 days)',
 'procedure',true,'whys',
 '[{"name":"Lisa Johnson","phone":"(713) 555-0391","statement":"Saw the pipe section fall from the rack. Load was being swung over the storage area."}]',
 '[{"description":"Review crane lift plan requirements — no lifts over stored materials","assignee":"Mike Chen","due_date":"2026-03-01","status":"Open","priority":"critical"},{"description":"Inspect all temporary storage racks for stability and load limits","assignee":"Mike Chen","due_date":"2026-03-05","status":"Open","priority":"high"}]',
 '[{"why":"Why 1","answer":"Pipe section fell from temporary rack during crane lift"},{"why":"Why 2","answer":"Crane swing path passed directly over storage area"},{"why":"Why 3","answer":"Lift plan did not account for proximity to stored materials"},{"why":"Why 4","answer":"Lift plan review process was abbreviated due to schedule pressure"},{"why":"Why 5","answer":"MOC process for crane operations did not require exclusion zone documentation"}]',
 '[]',
 'Patricia','Garcia','safety@company.com','(713) 555-0100',
 'Safety','Pasadena','HSE Coordinator',
 '2026-02-20T10:45:00Z','2026-02-25T09:00:00Z'),

-- 6. Observation — Freeport
('INC-2026-02-0203','Closed','observation','low','2026-02-14','11:00',
 'Freeport','Cooling Tower','During routine safety observation walk, HSE coordinator noted that two operators were not wearing required hearing protection in the designated hearing conservation area around the cooling tower. No injury occurred. Employees were counseled on-site and PPE was provided.',
 'Employees counseled on-site. Proper hearing protection provided immediately.',
 '',
 'employee','William','Kim','EMP-028','Operator I','Operations',
 '2022-11-05','Angela Brown','angela.brown@company.com',
 '','','',0,0,
 'First aid only','yes',false,'Not recordable — Near miss/observation',
 'training',false,'whys',
 '[]',
 '[{"description":"Post additional hearing protection reminder signs at CT entrance","assignee":"Angela Brown","due_date":"2026-02-21","status":"Closed","priority":"low"}]',
 '[]','[]',
 'Angela','Brown','safety@company.com','(713) 555-0100',
 'Safety','Freeport','HSE Coordinator',
 '2026-02-14T11:30:00Z','2026-02-21T08:00:00Z'),

-- 7. Ergonomic injury — Port Arthur
('INC-2026-01-0301','Closed','injury','medium','2026-01-28','14:00',
 'Port Arthur','Warehouse','Employee reported onset of lower back pain following a full shift of manual bag handling operations. Employee was moving 50-lb bags of catalyst without use of the material handling cart that was available. Incident classified as ergonomic/overexertion.',
 'Employee relieved from manual handling duties. Referred to occupational health physician.',
 '',
 'employee','Sandra','Okafor','EMP-113','Operator I','Operations',
 '2023-03-18','Karen Davis','karen.davis@company.com',
 'Overexertion / Ergonomic','Torso / Back','Lower back',0,8,
 'Occupational therapy / PT','yes',true,'Recordable — Job Transfer / Restricted Duty (8 days)',
 'training',true,'whys',
 '[]',
 '[{"description":"Mandate use of material handling cart for all loads over 35 lbs","assignee":"Karen Davis","due_date":"2026-02-04","status":"Closed","priority":"high"},{"description":"Conduct ergonomics refresher training for warehouse team","assignee":"Angela Brown","due_date":"2026-02-14","status":"Closed","priority":"medium"}]',
 '[{"why":"Why 1","answer":"Employee performed manual handling without aid"},{"why":"Why 2","answer":"Employee was unaware of the material handling cart policy"},{"why":"Why 3","answer":"New employee onboarding did not cover ergonomic requirements"},{"why":"Why 4","answer":"Ergonomics training module was not included in role-specific onboarding"},{"why":"Why 5","answer":"Training curriculum had not been reviewed in 4 years"}]',
 '[]',
 'Robert','White','safety@company.com','(713) 555-0100',
 'Safety','Port Arthur','Safety Officer',
 '2026-01-28T15:20:00Z','2026-02-10T09:00:00Z'),

-- 8. Environmental — Deer Park
('INC-2026-01-0302','Closed','environmental','immediate','2026-01-22','06:45',
 'Deer Park','Tank Farm','Minor hydrocarbon release from a corroded drain valve on Tank T-14 during morning rounds. Approximately 15 gallons of intermediate product were released onto the concrete secondary containment bund. All material was contained within secondary containment. No product reached soil or drainage systems.',
 'Valve isolated immediately. Spill contained within secondary containment. Emergency response team activated per site spill plan. TCEQ notification made.',
 'Tank T-14, Drain Valve',
 'employee','David','Torres','EMP-061','Operator II','Operations',
 '2017-07-30','John Martinez','john.martinez@company.com',
 '','','',0,0,
 'First aid only','yes',false,'Not recordable',
 'equipment',false,'fishbone',
 '[]',
 '[{"description":"Replace corroded drain valve on Tank T-14","assignee":"John Martinez","due_date":"2026-01-25","status":"Closed","priority":"critical"},{"description":"Inspect all drain valves in Tank Farm for corrosion — 30-day inspection cycle","assignee":"John Martinez","due_date":"2026-02-22","status":"Closed","priority":"high"}]',
 '[]','[]',
 'Michael','Santos','safety@company.com','(713) 555-0100',
 'Safety','Deer Park','HSE Coordinator',
 '2026-01-22T07:30:00Z','2026-01-30T10:00:00Z'),

-- 9. Contractor incident — Baytown
('INC-2025-12-0401','Closed','contractor','high','2025-12-10','13:30',
 'Baytown','Unit 5','Contract employee from Acme Mechanical was struck by a swinging pipe during scaffolding removal. The pipe was not secured prior to the removal of a support bracket. Employee sustained a laceration on the forearm requiring stitches. Contractor safety supervisor was immediately notified.',
 'First aid applied on-site. Contractor employee transported to clinic. Scaffolding work suspended. Contractor HSE supervisor notified.',
 'Scaffolding materials, 2-inch pipe section',
 'contractor','Kevin','Walsh','CON-0281','Scaffolding Technician','Contractor',
 '2023-05-15','Sarah Thompson','sarah.thompson@company.com',
 'Struck By Object','Upper Extremity','Right forearm',1,0,
 'Emergency room visit','yes',true,'Recordable — Days Away From Work (1 days)',
 'procedure',true,'whys',
 '[{"name":"James Garcia","phone":"(713) 555-0509","statement":"Saw the pipe swing when the bracket was removed. No one secured it first."}]',
 '[{"description":"Require daily contractor toolbox talks to include specific hazard review","assignee":"Sarah Thompson","due_date":"2025-12-17","status":"Closed","priority":"high"},{"description":"Update contractor orientation to include site-specific scaffolding requirements","assignee":"Angela Brown","due_date":"2025-12-24","status":"Closed","priority":"medium"}]',
 '[]','[]',
 'Jennifer','Williams','safety@company.com','(713) 555-0100',
 'Safety','Baytown','Safety Officer',
 '2025-12-10T14:45:00Z','2025-12-20T11:00:00Z'),

-- 10. Near miss — Texas City
('INC-2025-12-0402','Closed','nearmiss','medium','2025-12-05','08:00',
 'Texas City','Control Room','High-pressure alarm on compressor K-401 was not acknowledged for 47 minutes during a busy shift turnover period. A potential overpressure condition was developing but was caught before reaching the relief valve setpoint. Operator attributed the delay to simultaneous alarms during shift change.',
 'Alarm acknowledged and investigated. Compressor load adjusted. Alarm management review initiated.',
 'Compressor K-401',
 'employee','Patricia','Cruz','EMP-095','Control Room Operator','Operations',
 '2016-01-08','Mike Chen','mike.chen@company.com',
 '','','',0,0,
 'First aid only','yes',false,'Not recordable — Near miss/observation',
 'management',false,'fmea',
 '[]',
 '[{"description":"Review alarm rationalization for K-401 high-pressure alarm — reduce nuisance alarms","assignee":"Mike Chen","due_date":"2025-12-19","status":"Closed","priority":"high"},{"description":"Implement alarm handover procedure during shift change","assignee":"Sarah Thompson","due_date":"2025-12-19","status":"Closed","priority":"critical"}]',
 '[]','[]',
 'Michael','Santos','safety@company.com','(713) 555-0100',
 'Safety','Texas City','HSE Coordinator',
 '2025-12-05T09:00:00Z','2025-12-15T14:00:00Z'),

-- 11. Property damage — Corporate HQ
('INC-2025-11-0501','Closed','property','low','2025-11-18','15:45',
 'Corporate HQ','Parking Lot','Employee''s personal vehicle was struck by a runaway shopping cart from the adjacent retail property during a windstorm. Minor dent to driver-side door. No injuries. Incident documented for insurance purposes.',
 'Incident documented. Employee provided with incident report for insurance claim. Facilities management notified.',
 '',
 'employee','Linda','Park','EMP-140','HR Coordinator','Administration',
 '2020-09-14','Karen Davis','karen.davis@company.com',
 '','','',0,0,
 'First aid only','no','Not recordable — Not work-related','not applicable',
 'environment',false,'whys',
 '[]','[]','[]','[]',
 'Angela','Brown','safety@company.com','(713) 555-0100',
 'Safety','Corporate HQ','Safety Officer',
 '2025-11-18T16:00:00Z','2025-11-20T09:00:00Z'),

-- 12. Illness/respiratory — Freeport
('INC-2025-11-0502','Closed','illness','high','2025-11-07','09:00',
 'Freeport','Lab Area','Lab technician reported difficulty breathing and eye irritation approximately 2 hours into shift. Investigation revealed improper storage of incompatible chemicals (ammonia and bleach-based cleaners) in the same enclosed cabinet, resulting in chloramine vapor formation. Employee was removed from area and evaluated.',
 'Employee removed from area. Lab ventilated. Medical evaluation performed. Incompatible chemicals separated and properly stored.',
 'Chemical: Ammonia (cleaner), Chemical: Bleach-based cleaner',
 'employee','Maria','Kowalski','EMP-078','Lab Technician','QA/QC',
 '2019-03-22','Angela Brown','angela.brown@company.com',
 'Respiratory','Head / Neck','Respiratory tract / eyes',0,2,
 'Emergency room visit','yes',true,'Recordable — Job Transfer / Restricted Duty (2 days)',
 'procedure',true,'whys',
 '[{"name":"Robert Wilson","phone":"(713) 555-0622","statement":"Noticed a strong chemical smell and saw employee was coughing before she left the room."}]',
 '[{"description":"Implement chemical segregation requirements for lab storage — post compatibility chart","assignee":"Angela Brown","due_date":"2025-11-14","status":"Closed","priority":"critical"},{"description":"Conduct chemical safety refresher for all QA/QC lab staff","assignee":"Angela Brown","due_date":"2025-11-21","status":"Closed","priority":"high"}]',
 '[{"why":"Why 1","answer":"Incompatible chemicals stored in same enclosed cabinet"},{"why":"Why 2","answer":"No chemical incompatibility chart was posted in storage area"},{"why":"Why 3","answer":"Chemical storage SOP did not address incompatibility segregation"},{"why":"Why 4","answer":"SOP was written before current chemical inventory was established"},{"why":"Why 5","answer":"No periodic review of lab SOPs had been completed in over 5 years"}]',
 '[]',
 'Patricia','Garcia','safety@company.com','(713) 555-0100',
 'Safety','Freeport','HSE Coordinator',
 '2025-11-07T10:30:00Z','2025-11-18T14:00:00Z'),

-- 13. Near miss — La Porte
('INC-2025-10-0601','Closed','nearmiss','medium','2025-10-25','11:15',
 'La Porte','Cooling Tower','During maintenance on the cooling tower fan assembly, a worker nearly dropped a 12-inch wrench from the elevated platform (approximately 40 feet) into an active process area below. The wrench struck the grating and was stopped. No one was struck. Tool tethering was not in use.',
 'Work stopped. Tool recovered. Drop prevention procedure reviewed with crew.',
 'Wrench (12-inch), Cooling Tower Fan Platform',
 'employee','Joseph','Hernandez','EMP-104','Maintenance Technician','Maintenance',
 '2021-11-01','Tony Rodriguez','tony.rodriguez@company.com',
 '','','',0,0,
 'First aid only','yes',false,'Not recordable — Near miss/observation',
 'procedure',false,'whys',
 '[]',
 '[{"description":"Require tool tethering for all elevated work above 6 feet","assignee":"Tony Rodriguez","due_date":"2025-11-01","status":"Closed","priority":"high"}]',
 '[]','[]',
 'Robert','Thompson','safety@company.com','(713) 555-0100',
 'Safety','La Porte','Safety Officer',
 '2025-10-25T12:00:00Z','2025-11-01T09:00:00Z'),

-- 14. Injury — Pasadena
('INC-2025-10-0602','Closed','injury','medium','2025-10-14','08:30',
 'Pasadena','Warehouse','Employee tripped over an unsecured extension cord running across a main walkway in the warehouse during morning shift setup activities. Employee fell forward and sustained a contusion to the right palm and minor abrasion on the right knee. First aid was administered.',
 'First aid applied on-site. Extension cord removed from walkway and rerouted.',
 'Extension cord',
 'employee','Barbara','Nguyen','EMP-019','Logistics Coordinator','Logistics',
 '2017-04-25','Karen Davis','karen.davis@company.com',
 'Fall — Same Level','Lower Extremity','Right knee',0,0,
 'First aid only','yes',false,'Not recordable — First aid only',
 'environment',false,'whys',
 '[]',
 '[{"description":"Install permanent raceways for all power connections in main warehouse walkways","assignee":"Karen Davis","due_date":"2025-10-28","status":"Closed","priority":"medium"}]',
 '[]','[]',
 'Jennifer','Williams','safety@company.com','(713) 555-0100',
 'Safety','Pasadena','Safety Officer',
 '2025-10-14T09:15:00Z','2025-10-22T10:00:00Z'),

-- 15. Near miss — Port Arthur
('INC-2025-09-0701','Closed','nearmiss','high','2025-09-19','07:00',
 'Port Arthur','Tank Farm','Operator discovered a partially open isolation valve on a condensate drain line during a routine area inspection. The valve should have been locked closed under an active work permit. Investigation revealed the permit was not returned to the control room and the lock was removed without authorization.',
 'Valve secured and locked. Permit system audit initiated. All active permits verified.',
 'Isolation valve, condensate drain line',
 'employee','Richard','Taylor','EMP-067','Operator I','Operations',
 '2020-10-15','John Martinez','john.martinez@company.com',
 '','','',0,0,
 'First aid only','yes',false,'Not recordable — Near miss/observation',
 'management',false,'fishbone',
 '[{"name":"Susan Anderson","phone":"(713) 555-0755","statement":"Found the valve during walkthrough. Permit tag was not on the valve."}]',
 '[{"description":"Audit all active permits against field conditions — within 24 hours","assignee":"John Martinez","due_date":"2025-09-20","status":"Closed","priority":"critical"},{"description":"Retrain all Operations staff on LOTO/permit-to-work closeout requirements","assignee":"Angela Brown","due_date":"2025-10-03","status":"Closed","priority":"high"}]',
 '[]','[]',
 'Michael','Santos','safety@company.com','(713) 555-0100',
 'Safety','Port Arthur','HSE Coordinator',
 '2025-09-19T08:00:00Z','2025-09-30T11:00:00Z'),

-- 16. Injury — Baytown
('INC-2025-09-0702','Open','injury','immediate','2025-09-08','06:15',
 'Baytown','Unit 5','Employee was performing an emergency shutdown procedure when high-pressure steam was released from a manual bypass valve that had been inadvertently left open. Employee sustained first-degree burns to the right forearm. Area was immediately evacuated.',
 'Emergency shutdown completed. Employee transported to hospital emergency room. Area isolated. Emergency response activated.',
 'Manual bypass valve, High-pressure steam (300 PSI)',
 'employee','Thomas','Jackson','EMP-038','Operator II','Operations',
 '2018-06-20','Sarah Thompson','sarah.thompson@company.com',
 'Thermal (Heat/Cold)','Upper Extremity','Right forearm',5,0,
 'Emergency room visit','yes',true,'Recordable — Days Away From Work (5 days)',
 'human-error',true,'whys',
 '[{"name":"James White","phone":"(713) 555-0816","statement":"Heard the release and saw the steam. Employee was struck before he could step back."}]',
 '[{"description":"Review emergency shutdown checklist — add verification of all bypass valve positions","assignee":"Sarah Thompson","due_date":"2025-09-15","status":"Open","priority":"critical"},{"description":"Install remote position indicators on all bypass valves in Unit 5","assignee":"Mike Chen","due_date":"2025-10-08","status":"Open","priority":"high"}]',
 '[{"why":"Why 1","answer":"Steam released when emergency shutdown initiated"},{"why":"Why 2","answer":"Bypass valve was left in open position from previous maintenance"},{"why":"Why 3","answer":"Post-maintenance valve lineup verification was not completed"},{"why":"Why 4","answer":"Maintenance closeout checklist did not include bypass valve position"},{"why":"Why 5","answer":"Checklist was last revised in 2015 before bypass valve was installed"}]',
 '[]',
 'Jennifer','Williams','safety@company.com','(713) 555-0100',
 'Safety','Baytown','HSE Coordinator',
 '2025-09-08T07:30:00Z','2025-09-08T07:30:00Z'),

-- 17. Security — Corporate HQ
('INC-2025-08-0801','Closed','security','medium','2025-08-22','17:30',
 'Corporate HQ','Parking Lot','Unauthorized individual was observed attempting to access a restricted area of the facility using a tailgating method (following an authorized employee through a badge-access door). The individual was stopped by security personnel before gaining access. Police were notified.',
 'Unauthorized individual detained and escorted off premises. Police notified. Incident reported to security management.',
 '',
 'employee','Unknown','Unknown','N/A','N/A','N/A',
 '2000-01-01','Karen Davis','karen.davis@company.com',
 '','','',0,0,
 'First aid only','yes',false,'Not recordable',
 'procedure',false,'fishbone',
 '[]',
 '[{"description":"Conduct security awareness training — anti-tailgating procedures","assignee":"Karen Davis","due_date":"2025-09-05","status":"Closed","priority":"high"},{"description":"Review badge-access audit logs — identify all tailgating events in past 30 days","assignee":"Karen Davis","due_date":"2025-08-29","status":"Closed","priority":"medium"}]',
 '[]','[]',
 'Angela','Brown','safety@company.com','(713) 555-0100',
 'Safety','Corporate HQ','Safety Officer',
 '2025-08-22T18:00:00Z','2025-09-01T09:00:00Z'),

-- 18. Hearing loss — Freeport
('INC-2025-08-0802','In Progress','illness','medium','2025-08-10','09:00',
 'Freeport','Cooling Tower','Annual audiometric testing identified a Standard Threshold Shift (STS) in the left ear for an employee who works primarily in the cooling tower area. Employee reports never wearing double hearing protection despite the area designation requiring it. Baseline shift confirmed by follow-up testing.',
 'Employee referred to occupational audiologist. Enrolled in hearing conservation program. Removed from noise-hazardous tasks pending evaluation.',
 '',
 'employee','Carlos','Moore','EMP-126','Operator II','Operations',
 '2016-05-10','Angela Brown','angela.brown@company.com',
 'Repetitive Motion','Head / Neck','Left ear',0,0,
 'Physician / clinic visit','yes',true,'Recordable — Medical Treatment Beyond First Aid',
 'training',true,'whys',
 '[]',
 '[{"description":"Audit hearing protection compliance in cooling tower area — spot checks 3x per week","assignee":"Angela Brown","due_date":"2025-08-24","status":"Open","priority":"high"},{"description":"Update annual hearing conservation training to include STS consequences","assignee":"Angela Brown","due_date":"2025-09-10","status":"Open","priority":"medium"}]',
 '[]','[]',
 'Patricia','Garcia','safety@company.com','(713) 555-0100',
 'Safety','Freeport','HSE Coordinator',
 '2025-08-10T10:30:00Z','2025-08-15T09:00:00Z');
