#!/usr/bin/env node
/**
 * set-env.js — Reads environment variables and writes the Angular
 * environment files so that no secrets live in source control.
 *
 * Usage:
 *   node scripts/set-env.js          # writes dev environment
 *   node scripts/set-env.js --prod   # writes prod environment
 *
 * Required env vars (see .env.example):
 *   SUPABASE_URL, SUPABASE_ANON_KEY
 */

const fs = require('fs');
const path = require('path');

const isProd = process.argv.includes('--prod');

const supabaseUrl = process.env.SUPABASE_URL || 'https://tnlxzzjxqourhjvunuxi.supabase.co';
const supabaseKey = process.env.SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRubHh6emp4cW91cmhqdnVudXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MDI4OTYsImV4cCI6MjA4OTA3ODg5Nn0.2XmejeUrjaHRLh7Ma-b0eiwwG4TAvbkb-LJa1IiR4os';

const content = `// AUTO-GENERATED by scripts/set-env.js — do NOT edit manually
export const environment = {
  production: ${isProd},
  supabaseUrl: '${supabaseUrl}',
  supabaseKey: '${supabaseKey}',
};
`;

const target = isProd
  ? path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts')
  : path.join(__dirname, '..', 'src', 'environments', 'environment.ts');

fs.writeFileSync(target, content, 'utf-8');
console.log(`✅ Wrote ${isProd ? 'production' : 'development'} environment → ${target}`);
